package:
  name: influxd
  # Note that we needed to pin the version of rust to 1.82.0
  # since this release fails to compile with 1.83.0. There is
  # a commit which will fix it but it is not released yet.
  # So, for the next bump, please remove the `rust=1.82.0` pinning.
  version: 2.7.11
  epoch: 5
  description: Scalable datastore for metrics, events, and real-time analytics
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - coreutils
      - curl
      - go
      - rust=1.82.0

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/influxdata/influxdb
      tag: v${{package.version}}
      expected-commit: fbf5d4ab5e65d3a3661aa52e1d05259d19a6a81b
      destination: influxdb

  - uses: go/bump
    with:
      deps: github.com/hashicorp/go-retryablehttp@v0.7.7 golang.org/x/crypto@v0.31.0 golang.org/x/net@v0.33.0
      modroot: influxdb

  - runs: |
      cd influxdb
      unset LDFLAGS

      make generate-web-assets

      make influxd
      mkdir -p ${{targets.destdir}}/usr/bin
      mv bin/linux/influxd ${{targets.destdir}}/usr/bin

      mkdir -p ${{targets.destdir}}/etc/defaults/influxdb2/
      mv ../default-config.yml ${{targets.destdir}}/etc/defaults/influxdb2/config.yml

  - uses: strip

subpackages:
  - name: influxd-oci-entrypoint
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/bin
          mv entrypoint.sh ${{targets.subpkgdir}}/usr/bin/
    dependencies:
      runtime:
        - busybox
        - bash
        - yq

  - name: ${{package.name}}-${{package.version}}-bitnami-compat
    description: "compat package with bitnami/influxdb image"
    pipeline:
      - uses: bitnami/compat
        with:
          image: influxdb
          version-path: 2/debian-12
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/opt/bitnami/influxd/bin
          cp ${{targets.destdir}}/usr/bin/influxd ${{targets.subpkgdir}}/opt/bitnami/influxd/bin/influxd
    test:
      environment:
        contents:
          packages:
            - curl
      pipeline:
        - name: version tests
          runs: |
            /opt/bitnami/influxd/bin/influxd version | grep ${{package.version}}
        - name: Start the influxd server
          uses: test/daemon-check-output
          with:
            start: |
              /opt/bitnami/influxd/bin/influxd run
            timeout: 60
            expected_output: |
              Welcome to InfluxDB
              Starting
              Listening
            post: |
              #!/bin/sh -e
              url=http://localhost:8086
              response=$(curl -s -o /dev/null -w "%{http_code}" "$url")
              if [ "$response" -ne 200 ]; then
                echo "Error: InfluxDB did not start correctly."
                exit 1
              fi
              html=$(curl -s "$url")
              if [ -z "$html" ]; then
                echo "Got empty HTML content from $url"
                exit 1
              fi
              echo "$html" | grep -q "InfluxDB is a time series platform" || {
                echo "response from $url did not contain \"InfluxDB is a time series platform\""
                exit 1
              }
              echo "InfluxDB instance is up"

update:
  enabled: true
  github:
    identifier: influxdata/influxdb
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        influxd --help
        influxd version
