package:
  name: zipkin
  version: 3.5.0
  epoch: 0
  description: Zipkin distributed tracing system
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - bash
      - busybox
      - ca-certificates
      - openjdk-21-default-jvm

data:
  - name: openjdk-versions
    items:
      21: "/usr/lib/jvm/java-21-openjdk"

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - maven
      - openjdk-21

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openzipkin/zipkin
      tag: ${{package.version}}
      expected-commit: 0f8fc88d33131dc938532322e19126def8cad8e8
  - uses: maven/pombump
  - runs: |
      export JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
      ./build-bin/maven/maven_build_or_unjar io.zipkin zipkin-server ${{package.version}} exec
      mv zipkin-server zipkin
      mkdir -p ${{targets.destdir}}/usr/share/zipkin
      cp -av zipkin/* ${{targets.destdir}}/usr/share/zipkin/


subpackages:
  - name: zipkin-slim
    dependencies:
      runtime:
        - bash
        - busybox
        - ca-certificates
        - openjdk-21-default-jvm
    pipeline:
      - runs: |
          export JAVA_HOME="/usr/lib/jvm/java-21-openjdk"
          ./build-bin/maven/maven_build_or_unjar io.zipkin zipkin-server ${{package.version}} slim
          mv zipkin-server zipkin-slim
          mkdir -p ${{targets.subpkgdir}}/usr/share/zipkin-slim
          cp -av zipkin-slim/* ${{targets.subpkgdir}}/usr/share/zipkin-slim/
    

update:
  enabled: true
  github:
    identifier: openzipkin/zipkin
    use-tag: true
